[[tectonic]]
arch = "aarch64"
git-tree-sha1 = "61175eadbf3fb7cb77587340317e995380e200db"
os = "macos"

    [[tectonic.download]]
    sha256 = "1df70b2dabd7fe350ea94f3844f1b9814d7dc19625c99790b532fec4b57c3bf8"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.aarch64-apple-darwin.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af4e2e42444533d5e1b7fab4ef50e9ca55f008e1"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "47388b6ee805e19172d3b5837a0bc51aec855ff9d046611284d6f69cf89a89f1"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.aarch64-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aac3cb963d4cdc37781809727062004aa7c1bb70"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "40ba05cfa9ddf89ffe74c002627d589f32bb7f047fd7fd5aacd2f4a8c569f4bd"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.aarch64-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bdf899ab1fc0ab9c05369553b71a3630ec4f07e7"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "4f3b87f6dccbbe9a3f4c7de836717ab4d48408403b05b7e821631e08575a19c2"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.aarch64-linux-musl-cxx03.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a3df52f722726d1eb1d7b0ead8ebae3f90aa52c"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "70a8a6db9a7d64f8b0658d2dfa784bb52e018d59a19082f9af06128e89c07aeb"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.aarch64-linux-musl-cxx11.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bc5f08a9eef605d2b7359947a4507734fc396c7"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "d81c6f8d629869fb6d764fcbe2c917f32e49ffff55cbb67cd5dab4876041d127"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f875b439d74b7c0f1992f71dea797bdd221ba569"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "dcbbcf141b223c1a42973e42f425f2080013d072bfe84885e730f488281dbf57"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11332bff0dec7079e1339e51d1dee78110ff7c12"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "1ea3198873f2705e1a808f6ee699412b6843fddcc33f4c3e7ad60f87ee9ae4d3"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05a3cda9bfb39ba8bda8314d4eaefecee179ceb6"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "beed162940470f073923410cfd449248ccb9257b6b1222f61438f0f7f9c660ff"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2ddaf4881900524d845c5d4a9f3a048597fe690"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "baa919433ba30c9cb9cda3ff2917c53fd519d321c8969c95fe3c944fe3bad160"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.i686-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ee5e052624c2c9b9a3d63530d0e9a526812c2da"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "5118e546e6a1bee32764c605dd4c82bec6e0de8ab0d6e8db0189ee3df92b5caa"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.i686-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e35dd2c3a50fe6d4dd0f9179c825cee3b67fa081"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "3f5a2213eb43d3b7abff7810bb4d7d53bf068ac4ed3d1a9e7b4ae3305be4b6c2"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.i686-linux-musl-cxx03.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fe19e8e9600cac02c1b387c1e83bf3bac18dcf8"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "51f0c7dd48c210bcc4cfc9c8ce9bc2bd56f3a32969853311d16009651229d518"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.i686-linux-musl-cxx11.tar.gz"
[[tectonic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2015c60480b152294512a9bafcece1c5fffa4fc"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "861860408d73aeca7a142493c084301f42a3c73f0037c7e66b2ec2b91d0bcd53"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50723014e9f7eca9ee618b6414c47bb65b0c82e9"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "ab7db1aea89ce354e1cf43e7dffedbd08a782b39bcc25fb832580339b558deaf"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "x86_64"
git-tree-sha1 = "32fe88a6ff4b1fbd9f66504b9da89d6356cb93fb"
os = "macos"

    [[tectonic.download]]
    sha256 = "3be448381e9a9cf3a38fc310dacd5ae17e82f2c3952fac0ef942c07b5d426604"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.x86_64-apple-darwin.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59c5594379b205e5251835d56e9e0503fb64647d"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "17cfd33a97345a6216cc2f426bd07c0bd98bc563ff4420645935f04907054be1"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.x86_64-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e0c0d5e8e359b3ba8bc37ed212d64a25a7846c1"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "c615a74576a38f9d91dbc381df9f21e5e4e44a781046c81d834b5af820ada526"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.x86_64-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dc865c877ab415dd569fedfe777eca0b48ed938"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "51c0b5efd44b496c87eb2a9b5b0ad25fb000981076ce5546344b284fcfde7a70"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.x86_64-linux-musl-cxx03.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76790cab897bbaa507d2a25a6e1830d441e26481"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "5a719b26872c7909c45fe395084e8722c03c6a5bdf7c35912be1056b320efedc"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.x86_64-linux-musl-cxx11.tar.gz"
[[tectonic]]
arch = "x86_64"
git-tree-sha1 = "34680c214f35e27f258d5017e17bf0903a0b15c7"
os = "freebsd"

    [[tectonic.download]]
    sha256 = "fc608585db086695e6dbea7e218b897b0f0feda911aff0e7a1e6518b724f8d9f"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.x86_64-unknown-freebsd.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea627f9aa102504548ff4ec38fac55b12d102074"
os = "windows"

    [[tectonic.download]]
    sha256 = "4802ec64ba95c19d36133847a08edcf5237bdb8d630f596703c0f6d49a97cf4c"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1ebc4990dd5d513af6396f5334738878d892fd8"
os = "windows"

    [[tectonic.download]]
    sha256 = "24d72f259a3771a291b7fc417fd520d74a4d9430cfbc070e75c20601a4d66256"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.12.0+0/tectonic.v0.12.0.x86_64-w64-mingw32-cxx11.tar.gz"
