[[tectonic]]
arch = "aarch64"
git-tree-sha1 = "26fe46dec594cb9f068729889006a2ec139f2511"
os = "macos"

    [[tectonic.download]]
    sha256 = "bce2385ace95c7f24c5977e1acb0eeb731dde24aeacf384206c1c02c4277ee3f"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.aarch64-apple-darwin.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5757e3e97b84924724b59fc3bfaa9a0c59022144"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "931393da0401706ec7abe770fdf8409e42796b2f1c8922101973e70d382cbfea"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.aarch64-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5287eb5d3ad384d062fc04a8b39c2b6e16cd941"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "452b572ed209e8a321bd9ee4adf33a7f0c4a17589135a73fa3a9a9c40ad0b8ac"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.aarch64-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6cbe4853d4d9fc5ff00026145637c9d7196a7f9"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "d7e567331418a86f612c3ec2f4109b91fb946f1bb7a455907379c874e5fb9773"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.aarch64-linux-musl-cxx03.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d09cb5b3c84b046a1db6534cadf5ff42c26b534"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "0c29cf04a6f944bbbc13c5ef1dd6424d264e55b578d439c981f324b134b77c55"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.aarch64-linux-musl-cxx11.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d929904077c9e3ef9e18fd30608a910c1e67f010"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "213aeb4cc079a067662db4bc65a682e8dce93953afb726b8384c760a83641236"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6af0ff089ba95cb0ceecde376153be1845204f1a"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "5a023625bbbb2974f7b78d9cdf1190abff0a8068213ab99f444b268cc1de6ab2"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90a4cad31ca4161809333bb448438110ca3b6d8a"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "23d48f905ed63a4aec81a6545c95600b798dc92b29b3af7069007884c777b281"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e75d1d7b438aa4ff47a713d4bd6185c78a03c16"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "7b3ccbb8a2f3affae50d586a3f39d631371318e9f213220e6a7aeaae4a83f77d"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f80ffe34e2a372e5518ee765b8eb4d3f6dc34ec"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "f96f9666dffe63ffff946896b6ecd68e8471e70588262bd4570a11143906cd7e"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.i686-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce5657beaa0e35ab438701a1133913a180018085"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "96e48e38890eeb5c30e64244a080e9ae488f896ef643b3d0b97e1456f074de36"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.i686-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c967204a7476413a623553f10611678a2028906f"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "598556e2c25d75708b3606a9c977d939e17547df76626caea12b4b9239a28b5b"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.i686-linux-musl-cxx03.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32b0410a67cde2705c758992d21d734d8d04a940"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "53a1a2e9fc0b4045b1df61e90de7b4dada955d4a62172f71b3c503a026e4b91a"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.i686-linux-musl-cxx11.tar.gz"
[[tectonic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "363b2cf38f12f17b8f9ac85efd4b9c19d84ac196"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "ce2e426a88e2dfab64760f36e6ee375bdb32bf33dd7e33f7001fd2161825bdaf"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fe91f47902588b5716e419409cc6822ae15d00a"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "536d0446f3ca8393480e64a0aa773967abeac0cd823f53a5c2b614f86ae252be"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "x86_64"
git-tree-sha1 = "9dc7efd1fa13f0fae6d824676bd2f8beabc4c99e"
os = "macos"

    [[tectonic.download]]
    sha256 = "00e0c9514b5f19c74650b82fb66a9ab36644665ccb7ffbe74ce9daa9183fbffe"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.x86_64-apple-darwin.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5cc603834b05e0c195b986de72d8db5226f3ea0"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "dbaeca6b9201a17f52e16d5fc35063bcbb41b68fc3d48c60d9adf41131eb5df0"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.x86_64-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2b30cb9817102158994bbd35c311cc8dda53b3e"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "842d925dfb2fc4fda1c1c78b2f6d8824a2acd53b66dac62b14c8e029dfc64e43"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70a603a50b24db44e82ea299243feda422ef8b66"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "41d83fcade4183e644737f09594701ab67fdb593025d13f47574686740d2d826"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.x86_64-linux-musl-cxx03.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8976e73633daa188c69495e506d9905ae10d3be"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "a61327ab06bed4ee19ddf1bfa081f274916486e20025bb747a34faeef16407be"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.x86_64-linux-musl-cxx11.tar.gz"
[[tectonic]]
arch = "x86_64"
git-tree-sha1 = "f39636b218477725ba935ada5cd91059e63f20ba"
os = "freebsd"

    [[tectonic.download]]
    sha256 = "c1f4296a06cab06a724a2aaf8a680f063baf134d18e1589eb0cf82ec552390bd"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.x86_64-unknown-freebsd.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afbcc63a1f9b3e15a47889957aa0fb01b5b13413"
os = "windows"

    [[tectonic.download]]
    sha256 = "e6b911a458ebed603b285a0716b21433fee50042e9391b231aa54db1199133ec"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9881c1835bcf0929d9f506c9ad75b7ec09fdfbee"
os = "windows"

    [[tectonic.download]]
    sha256 = "6af5c47a7a9cb606e552e062b98c2535470f2a65135448b43975e8dda89b7051"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.8.0+0/tectonic.v0.8.0.x86_64-w64-mingw32-cxx11.tar.gz"
