[[tectonic]]
arch = "aarch64"
git-tree-sha1 = "98916af7a9404543a29ea963c08b11b559063661"
os = "macos"

    [[tectonic.download]]
    sha256 = "a4025c244abf9370c7f57c6e5add61552d202c3428b3a0d0f6368a06f5e99369"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.aarch64-apple-darwin.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72c5b20588021107630c75707ca7b586db7c745a"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "64876daef0341c267954f42f6124503dca6f3b297256036445c3a41a33f151a3"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.aarch64-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83eaeb0dadcaba2d193d1391120822d953aa2a72"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "df09a0e4369f99df9c305d92ac339fca191ea7c6399997db098cd97477f7560f"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.aarch64-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2a9f22f3f8242a845bbd2457b5202f8e3d7d522"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "280eab5dc07fad6fcfbf804df26e00b90d80f45333a44591fc579700eff73ef5"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.aarch64-linux-musl-cxx03.tar.gz"
[[tectonic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "091be1192f23cb23fccd4cc8ed2b3a029ebced2c"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "fb3ef8507449e3c239bbe624ffe09e7ac0d88f9febf5eb73d8a348979c4cdcf9"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.aarch64-linux-musl-cxx11.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e020bcac4788a4d4fb90e81e24a056eb0ad7f847"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "2b65be4a920f72f22329396c2310823d86c1e689ad84d186af1326b05c1c7d5f"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8ab31d6bd255627f2f10f0dfc852fa263b556d5"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "093f79f796349f3d3065806694a1155133d6976745c81b7fe54f3d01ad27cd9b"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b01a5e126f9667565bd3685fb3d8678b6f9cadd7"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "efa3ba2cc978b115c59a88327736624719b5bbd52c429045c9731df05221fd36"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[tectonic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7508ea05b4492fa4b5994ca6f7cc3e3b56ba0591"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "973dd20ee8bf5015fdde1b552c1bedafb09d03ff99aa17c32c45d524053fccfb"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f4dde8130a90507c641f503a400bcb5e450d051"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "4edb08f4f079aa3fefd5790d09ac62dd9c6f1cad03ad8455dc9c48b980bd3698"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.i686-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31affcb85acce6b95b8d93ceb7f1e0da0deb7462"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "8eab468f307a71311653de0eb6fee061566a696544f4c3ef6d4d635314cd1c7e"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.i686-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25c559f856a964b8df39abdfaa02e2abe7411c8f"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "e26f1a0b65b145f70afe14da9af4f78b11ed756a03e4be939a7d453ee87269d9"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.i686-linux-musl-cxx03.tar.gz"
[[tectonic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e8018572af1e48ae4aa58097a6eec4fd7792d28"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "3f7b54d7df341d9ab147a81a9f936bb26c45e7929c163443a52732b7bc30fbcd"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.i686-linux-musl-cxx11.tar.gz"
[[tectonic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5db688da8b99631b51c418f82ea6af7562dd0a5d"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "5644e800dc651fa401c15fd4969848b88dc1bd48c50b177c8440ef24dc612cc7"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7248afe58c77547b9b18a208dd2e55f984b9dba"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "c5d10d8f0972ab33e67240715a33f12945abf9bdb09d5f23789a0e520b5a2af2"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "x86_64"
git-tree-sha1 = "bc647e833aef31c7d8178eed34f569678d07dc7b"
os = "macos"

    [[tectonic.download]]
    sha256 = "4ebcc06741687bda470b1db93af7c8f22e2e00e30e8fd39ce1d4d89176ee1ffe"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.x86_64-apple-darwin.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "089b93092e9c2349916077b511d540fdf321e22c"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "7d8b7332c2e49b80f6b9c5315f9d6a9ed47f00aef1d186d9d2970752ccce3a8d"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.x86_64-linux-gnu-cxx03.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84bfebc3ee45678f3487ac2503f13198c4e76eb0"
libc = "glibc"
os = "linux"

    [[tectonic.download]]
    sha256 = "1b7cfa571b821ed4c4581158a6308dbb9eefb04af7b673542175437fb1fdb3ce"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.x86_64-linux-gnu-cxx11.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95df5d8171c4825f5eb06184a924a6a03d4604e3"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "cc13f5de54cdb9d13dc7827f6fb2775acb75cbf883f8376d86a559ff12719394"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.x86_64-linux-musl-cxx03.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cea2cc4477810e51ed7aa718b6371c4ae5bf1591"
libc = "musl"
os = "linux"

    [[tectonic.download]]
    sha256 = "089136a5f65b60f31c09bac68751e8ec822717727152b31127137ad27ee3fe65"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.x86_64-linux-musl-cxx11.tar.gz"
[[tectonic]]
arch = "x86_64"
git-tree-sha1 = "0018fd95dbbdafd8c24c84d1320eb3b0150d7fbe"
os = "freebsd"

    [[tectonic.download]]
    sha256 = "67f927486da6ddbbf0f1027a87e46532dc4199f9e86f863e0ba969824e216eb0"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.x86_64-unknown-freebsd.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "839d3522d50716b47c15757e6ef26a87c72f6a43"
os = "windows"

    [[tectonic.download]]
    sha256 = "4826c0aa62288a4006b3ce31417061994f3e710c5d42bbac1e8ae9b998587ab1"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[tectonic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "177ed29d9ff5472967d660c5b817b2c32cdc04af"
os = "windows"

    [[tectonic.download]]
    sha256 = "7fa0f3195894ebe42791489962506a2ee238fe0484071e91e8d6f2f66286cb07"
    url = "https://github.com/JuliaBinaryWrappers/tectonic_jll.jl/releases/download/tectonic-v0.11.0+0/tectonic.v0.11.0.x86_64-w64-mingw32-cxx11.tar.gz"
